# GENERATE_CONVERSATION_TRANSCRIPT="""Convert this audio conversation between doctor and patient and 
# provide the transcript in the same language in which audio is available me response in this format :
# { "transcript":  " Doctor:
#     Patient:
#     Doctor:
#     Patient:
#     ",
#     "summary:"<summary of the transcript in the same language of the audio file  do not mention anything like conversation between patient and doctor simply start with very crysp summary>"
# }
# """

GENERATE_CONVERSATION_TRANSCRIPT="""Your task is to conver the audio file provided into english transcript and a english summary
Do not add anything extra 
provide me resposne in this format
{ "transcript":  "<transcript in the audio language of the audiofile or keep it empty> ",
    "summary:"<summary of the transcript in the same language of the audio file  do not mention anything like conversation between patient and doctor simply start with very crysp summary>",
    "transcript_english":  "<transcript in US english language of the audiofile or keep it empty> ",
    "summary_english:"<summary in US english language of the transcript in the same language of the audio file  do not mention anything like conversation between patient and doctor simply start with very crysp summary>"
}
"""

def get_ehr_generate_prompt(trasncript):
    prompt ="""Refer to the provided transcript and provide me a structured output in english for storing data into database 
    transcript:"""+trasncript+"""
    Strictly add proper new lines after every entity  
    I want to add data in this schema 
        past_medical_history = TextField(null=True) 
    phy_examination = TextField(null=True)
    assessment = TextField(null=True)
    current_medical_issue = TextField(null=True)
    last_admitted_date = DateField(null=True)
    last_admitted_summary = TextField(null=True) 

    so provide me response in this format in English language with proper new lines (\n) and spacings  :
    {
    "phy_examination":"",\n
    "assessment":"", \n
    "current_medical_issue":"",\n
    "last_admitted_summary":"",\n
    "last_admitted_date":"",\n
    "past_medical_history":"",\n
    }
     if any information is not mentioned in transcript then simply keep that value blank 
"""
    return prompt


def get_ehr_format_prompt(transcript=None,ehrs=None):
    prompt="""Here is ehr of a patient"""+ehrs+""" , I want you to add in these details to the transcript and create a super transcript containing combined information
    Here is the info that needs to be added"""+transcript+"""
    Provide me resposne in this format 
    {
    "phy_examination":"",
    "assessment":"",
    "current_medical_issue":"",
    "last_admitted_summary":"",
    "last_admitted_date":"",
    "past_medical_history":"",
    }
"""
    return prompt


def get_chat_response(data=None,prompt=None):
    final_prompt="""Refer to this data this data is combination of EHR , 
    patient details , model output of earlt detection model ,CXR , and
      heat map generated by deep learining model """+data+"""and provide a answer 
      to this question , Remember your answer should be rich with Medicall keywords :"""+prompt
    return final_prompt

def get_chat_response(prompt=None):
    final_prompt="""Refer to this data this data is combination of EHR , 
    patient details , model output of earlt detection model ,CXR , and
      heat map generated by deep learining model and provide a answer 
      to this question , Remember your answer should be rich with Medicall keywords :"""+prompt
    return final_prompt