import React, { useState, useEffect } from "react";
import { CiLock, CiUnlock } from "react-icons/ci";
import { CiSaveDown1 } from "react-icons/ci";
import * as constant from "../constant";
import { saveAs } from "file-saver";
const PopupReport1 = ({ openPopUp, employee_id, closePopUp }) => {
  const [report, setReport] = React.useState(constant.REPORT);
  const [isLeftEditable, setIsLeftEditable] = useState(false);
  const [leftText, setLeftText] = useState(report);
  const [rightText, setRightText] = useState(
    "Clinical History- Former smoker of 15-pack years Radiation \n \nDose - CTDIvol: 2.5 mG (miligrays)\n\n \t\t-  DLP: 80 mG cm (miligrays-centimeters)"
  );
  if (openPopUp !== true) return null;

  function handleLeftEdit() {
    setIsLeftEditable(true);
  }

  function handleLeftSave() {
    setIsLeftEditable(false);
  }

  function handleLeftChange(e) {
    setLeftText(e.target.value);
  }

  function handleRightChange(e) {
    setRightText(e.target.value);
  }

  function handleLosePopUp(e) {
    if (e.target.id === "ModelContainer") {
      closePopUp();
    }
  }
  const handleDownload = () => {
    const pdfFile = require("../Draft_Radiology_12345.pdf");
    saveAs(pdfFile, "Draft_Radiology_12345.pdf");
  };

  return (
    <div
      id="ModelContainer"
      onClick={handleLosePopUp}
      className="fixed inset-0 bg-black flex justify-center items-center bg-opacity-20 backdrop-blur-sm "
      style={{ backdropFilter: "blur(8px)", zIndex: 9999 }}
    >
      <div className="p-2 text-black bg-[#F0F0F0] w-[70%] shadow-inner border-e-emerald-600 rounded-lg py-5  h-[80%]">
        <div className="flex w-[100%] h-[95%]">
          <div className="w-[100%] h-[100%] pr-1">
            <div className="h-[100%]">
              <div className="flex w-[100%] ">
                <div className="flex justify-start font-bold w-[100%]">
                  <h2 className="">Draft Report Generated by AI :</h2>
                </div>
                <div className="flex justify-end w-[100%]">
                  {!isLeftEditable ? (
                    <button
                      className="border border-gray-500 bg-green-300 p-1 rounded-lg"
                      onClick={handleLeftEdit}
                    >
                      <CiLock size={27} />
                    </button>
                  ) : (
                    <button
                      className="border border-gray-500 bg-red-300 p-1 rounded-lg"
                      onClick={handleLeftSave}
                    >
                      <CiUnlock size={27} />
                    </button>
                  )}
                </div>
              </div>

              <textarea
                className="border border-gray-500 text-black mt-3 rounded-lg w-[100%] h-[80%]"
                readOnly={!isLeftEditable}
                value={leftText !== "" ? leftText : report}
                onChange={handleLeftChange}
              />
            </div>
          </div>
        </div>
        <div className="flex  w-[100%] h-[5%] justify-center items-center">
          <button
            className="flex bg-[#FE7223] hover:bg-[#FE5A55] p-2 rounded-lg mb-5 text-black "
            onClick={() => {
              handleDownload();
            }}
          >
            <CiSaveDown1 size={30} />
            <span className="text-m text-black mt-0.5 ">
              Export Radiology Draft Report
            </span>
          </button>
        </div>
      </div>
    </div>
  );
};

export default PopupReport1;